In [1]:
import pandas as pd
import requests as req

In [2]:
url =f"https://www.iposcoop.com/2025-pricings/"
headers = {
        'User-Agent': (
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
            'AppleWebKit/537.36 (KHTML, like Gecko) '
            'Chrome/58.0.3029.110 Safari/537.3'
        )
    }
from io import StringIO

def getdata(url):
    try:
            response = req.get(url, headers=headers, timeout=10)
            response.raise_for_status()

            # Wrap HTML text in StringIO to avoid deprecation warning
            # "Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object."
            html_io = StringIO(response.text)
            tables = pd.read_html(html_io)

            if not tables:
                raise ValueError(f"No tables found.")

            return tables[0]

    except req.exceptions.RequestException as e:
            print(f"Request failed: {e}")
    except ValueError as ve:
            print(f"Data error: {ve}")
    except Exception as ex:
            print(f"Unexpected error: {ex}")

    return pd.DataFrame()

In [3]:
df=getdata(url)

In [4]:
df.columns=df.columns.str.replace(" ","_").str.lower()

In [5]:
df.head(1)

,company,symbol,industry,offer_date,shares_(millions),offer_price,1st_day_close,current_price,return,scoop_rating
0,Vine Hill Capital Investment Corp. II,VHCPU,Blank Check,12/18/2025,20.0,$10.00,$0.00,$0.00,0.00%,S/O

In [6]:
from datetime import datetime

In [7]:
df_filtered=df[((pd.to_datetime(df['offer_date'], format='mixed')) < datetime(2025,9,1)) & ( (pd.to_numeric(df['return'].str.replace("%",""), errors='coerce')) !=0 ) ]

In [8]:
len(df_filtered)

146

In [9]:
df_filtered.head(1)

,company,symbol,industry,offer_date,shares_(millions),offer_price,1st_day_close,current_price,return,scoop_rating
68,"Picard Medical, Inc.",PMI,Health Care,8/29/2025,4.3,$4.00,$4.59,$1.68,-58.00%,S/O

In [10]:
import yfinance as yf
import numpy as np

In [11]:
import time
g=0
stocks_df = pd.DataFrame({'A' : []})

for i,ticker in enumerate(df_filtered["symbol"]):
  print(i,ticker)

  

  # Work with stock prices
  try:
    ticker_obj = yf.Ticker(ticker)

    # historyPrices = yf.download(tickers = ticker,
    #                    period = "max",
    #                    interval = "1d")
    df2 = ticker_obj.history(
                      period = "max",
                      interval = "1d")
    
    # sleep 1 sec between downloads - not to overload the API server
    df2["ticker"] = ticker
    df2["year"]= df2.index.year
    df2["month"] = df2.index.month
    df2["weekday"] = df2.index.weekday
    df2["date"] = df2.index.date
    time.sleep(1)
    if stocks_df.empty:
        stocks_df=df2
    else:
      stocks_df = pd.concat([stocks_df,df2], ignore_index=True)
    g=g+1
  except Exception as e:
    print(e)

print(g)

0 PMI
1 TGHL
2 THH
3 CURX
4 CEPF
5 ETS
6 YMT
7 NUTR
8 PPCB
9 BUUU
10 MIAX
11 RYOJ
12 BLSH
13 NSRX
14 MAGH
15 AVBH
16 DKI
17 EFTY
18 HTFL
19 FLY
20 WYFI
21 CTW
22 HCMAU
23 FIG
24 SI
25 AMBQ
26 YMAT
27 ARX
28 LHAI
29 MH
30 CARL
31 CRE
32 TDIC
33 NIQ
34 MJID

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: MJID"}}}
$MJID: possibly delisted; no timezone found

'Index' object has no attribute 'year'
35 KMRK
36 MGRT
37 ALM
38 DLXY
39 MSGY
40 ANPA
41 TLIH
42 MAMK
43 CV
44 EMPG

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: EMPG"}}}
$EMPG: possibly delisted; no timezone found

'Index' object has no attribute 'year'
45 GRAN
46 CAEP

$CAEP: possibly delisted; no timezone found

'Index' object has no attribute 'year'
47 JCAP
48 JLHL
49 FMFC
50 CAI
51 EGG
52 SLDE
53 MENS
54 AIRO
55 CHYM
56 VNTG
57 ASIC
58 VOYG
59 JEM
60 OMDA
61 CRCL
62 PTNM

$PTNM: possibly delisted; no timezone found

'Index' object has no attribute 'year'
63 HNGE
64 MNTN
65 ANTA
66 ETOR
67 OMSE
68 APUS
69 AII
70 AHL

$AHL: possibly delisted; no timezone found

'Index' object has no attribute 'year'
71 CEPT

$CEPT: possibly delisted; no timezone found

'Index' object has no attribute 'year'
72 SDM

$SDM: possibly delisted; no timezone found

'Index' object has no attribute 'year'
73 CIGL
74 PFAI
75 TMDE
76 CHA
77 EDHL
78 HXHX
79 ATHR
80 CUPR
81 IOTR
82 MB
83 CIIT
84 FATN
85 RYET
86 BLIV
87 LHSW
88 SMA
89 TOPW
90 ENGS
91 WTF
92 WXM
93 CRWV
94 NCT
95 WFF
96 EPSM
97 NTHI
98 LGPS
99 BIYA
100 MCRP
101 SAGT
102 ADVB
103 TBH

$TBH: possibly delisted; no timezone found

'Index' object has no attribute 'year'
104 CAPS
105 KMTS
106 PN
107 LZMH
108 WETO
109 STAK
110 BMGL
111 WGRX

$WGRX: possibly delisted; no timezone found

'Index' object has no attribute 'year'
112 NNNN
113 NPB
114 AARD
115 KRMN
116 SAIL
117 XHLD
118 AGH

$AGH: possibly delisted; no timezone found

'Index' object has no attribute 'year'
119 SION
120 TTAM
121 EPWK

$EPWK: possibly delisted; no timezone found

'Index' object has no attribute 'year'
122 FBGL
123 CJMB
124 HCAI
125 PLUT
126 INR
127 MAZE
128 MTSR

$MTSR: possibly delisted; no timezone found

'Index' object has no attribute 'year'
129 BBNX
130 SFD
131 AAPG
132 VG
133 SKBL

$SKBL: possibly delisted; no timezone found

'Index' object has no attribute 'year'
134 MCTR

$MCTR: possibly delisted; no timezone found

'Index' object has no attribute 'year'
135 DGNX
136 TOPP
137 FLOC
138 PCLA
139 HKPD
140 UFG
141 MIMI
142 MASK
143 CEPO
144 ZYBT
145 INLF
132

In [12]:
print(g)

132

In [13]:
stocks_df.head(1)

,Open,High,Low,Close,Volume,Dividends,Stock Splits,ticker,year,month,weekday,date,Capital Gains
0,210.5,356.0,209.5,229.5,126794,0.0,0.0,PMI,2025,8,4,2025-08-29,NaN

In [19]:
stocks_df

,Open,High,Low,Close,Volume,Dividends,Stock Splits,ticker,year,month,weekday,date,Capital Gains,growth_252d
0,210.50,356.00,209.500,229.50,126794,0.0,0.0,PMI,2025,8,4,2025-08-29,NaN,NaN
1,242.50,267.50,232.500,257.00,98358,0.0,0.0,PMI,2025,9,1,2025-09-02,NaN,NaN
2,257.00,270.00,250.500,264.50,35960,0.0,0.0,PMI,2025,9,2,2025-09-03,NaN,NaN
3,265.50,287.50,265.000,286.50,28074,0.0,0.0,PMI,2025,9,3,2025-09-04,NaN,NaN
4,288.00,295.00,282.500,292.50,18572,0.0,0.0,PMI,2025,9,4,2025-09-05,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68078,2.72,2.77,2.630,2.66,18600,0.0,0.0,INLF,2026,9,0,2026-09-21,NaN,1014.135342
68079,2.65,2.95,2.650,2.80,40400,0.0,0.0,INLF,2026,9,1,2026-09-22,NaN,931.428587
68080,2.86,2.91,2.834,2.91,16300,0.0,0.0,INLF,2026,9,2,2026-09-23,NaN,922.611673
68081,2.90,3.00,2.890,2.95,9533500,0.0,0.0,INLF,2026,9,3,2026-09-24,NaN,872.135596
68082,6.25,6.87,4.570,5.10,49266900,0.0,0.0,INLF,2026,9,4,2026-09-25,NaN,512.000000

In [31]:
stocks_df["growth_252d"] = (
    stocks_df["Close"] /
    stocks_df.groupby("ticker")["Close"].shift(252)
    
)

In [32]:

stocks_df['volatility'] = (
    stocks_df.groupby('ticker')['Close']
    .transform(lambda x: x.rolling(30).std() * np.sqrt(252))
)

In [33]:
stocks_df['Sharpe'] = (
    (stocks_df['growth_252d'] - 0.05)
    / stocks_df['volatility']
)

In [34]:
final_df = stocks_df[stocks_df.date == pd.to_datetime('2026-09-11').date()]

final_df.describe()

d:\stock-markets-analytics-zoomcamp-2026-course\.venv\Lib\site-packages\pandas\core\nanops.py:1028: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

,Open,High,Low,Close,Volume,Dividends,Stock Splits,year,month,weekday,Capital Gains,growth_252d,volatility,Sharpe
count,132.000000,132.000000,132.000000,132.000000,1.320000e+02,132.0,132.0,132.0,132.0,132.0,1.0,130.000000,131.000000,130.000000
mean,12.807015,13.154650,12.485896,12.774863,1.248286e+06,0.0,0.0,2026.0,9.0,4.0,0.0,1.057613,27.516340,inf
std,19.227725,19.579373,18.882784,19.149571,3.184344e+06,0.0,0.0,0.0,0.0,0.0,NaN,3.049007,66.879183,NaN
min,0.116000,0.129000,0.115000,0.125000,0.000000e+00,0.0,0.0,2026.0,9.0,4.0,0.0,0.001005,0.000000,-0.040147
25%,2.070000,2.235750,2.019000,2.077500,2.297500e+04,0.0,0.0,2026.0,9.0,4.0,0.0,0.141035,2.301309,0.012042
50%,4.505000,4.790000,4.475000,4.565000,1.708500e+05,0.0,0.0,2026.0,9.0,4.0,0.0,0.594534,7.885748,0.050142
75%,17.397501,17.471250,16.732501,17.224999,9.976250e+05,0.0,0.0,2026.0,9.0,4.0,0.0,1.038821,23.452319,0.133619
max,120.500000,120.500000,120.425003,120.425003,2.168250e+07,0.0,0.0,2026.0,9.0,4.0,0.0,33.638270,627.698106,inf

In [35]:
stocks_df

,Open,High,Low,Close,Volume,Dividends,Stock Splits,ticker,year,month,weekday,date,Capital Gains,growth_252d,volatility,Sharpe
0,210.50,356.00,209.500,229.50,126794,0.0,0.0,PMI,2025,8,4,2025-08-29,NaN,NaN,NaN,NaN
1,242.50,267.50,232.500,257.00,98358,0.0,0.0,PMI,2025,9,1,2025-09-02,NaN,NaN,NaN,NaN
2,257.00,270.00,250.500,264.50,35960,0.0,0.0,PMI,2025,9,2,2025-09-03,NaN,NaN,NaN,NaN
3,265.50,287.50,265.000,286.50,28074,0.0,0.0,PMI,2025,9,3,2025-09-04,NaN,NaN,NaN,NaN
4,288.00,295.00,282.500,292.50,18572,0.0,0.0,PMI,2025,9,4,2025-09-05,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68078,2.72,2.77,2.630,2.66,18600,0.0,0.0,INLF,2026,9,0,2026-09-21,NaN,0.000986,12.614773,-0.003885
68079,2.65,2.95,2.650,2.80,40400,0.0,0.0,INLF,2026,9,1,2026-09-22,NaN,0.001074,12.137703,-0.004031
68080,2.86,2.91,2.834,2.91,16300,0.0,0.0,INLF,2026,9,2,2026-09-23,NaN,0.001084,12.083138,-0.004048
68081,2.90,3.00,2.890,2.95,9533500,0.0,0.0,INLF,2026,9,3,2026-09-24,NaN,0.001147,11.880555,-0.004112
68082,6.25,6.87,4.570,5.10,49266900,0.0,0.0,INLF,2026,9,4,2026-09-25,NaN,0.001953,12.155549,-0.003953

In [38]:
# 1. Feature Engineering: Calculate the 12 future growth columns
growth_cols = []
for i in range(1, 13):
    col_name = f'future_growth_{i}_m'
    growth_cols.append(col_name)
    
    # We use groupby('ticker') before shifting so we don't accidentally 
    # shift the closing price of one stock into a completely different stock!
    stocks_df[col_name] = stocks_df.groupby('ticker')['Close'].shift(-21 * i) / stocks_df['Close']

In [39]:
# 2. Identify Entry Points: Find the first available trading day (min_date)
min_dates = stocks_df.groupby('ticker', as_index=False)['date'].min()

In [40]:
ipo_starting_data = pd.merge(stocks_df, min_dates, on=['ticker', 'date'], how='inner')

In [41]:
desc_stats = ipo_starting_data[growth_cols].describe()

In [42]:
medians = desc_stats.loc['50%']
highest_growth_month = medians.idxmax()
highest_median_value = medians.max()
print(f"The highest median is in '{highest_growth_month}' with a value of {highest_median_value:.4f}")

The highest median is in 'future_growth_1_m' with a value of 0.9354